### ISSUE TITLE
Retribution data dump link

### ISSUE THREAD

**Issue by ErikEvenson** [gtaylor/django-eve-db#15]
Can you include a download or a link to a download for the latest SQLite data dump that works with your tool?

Thanks for the code!

**Comment by zweizeichen** [comment]
Hey Erik,
try this one: http://files.zweizeichen.org/retribution-1.1-84566.zip

**Comment by gtaylor** [comment]
I updated that on our wiki: https://github.com/gtaylor/django-eve-db/wiki/Getting-started

@zweizeichen Maybe you can help me remember to update that with each release, assuming you'll do further conversions in the future :)

**Comment by ErikEvenson** [comment]
Excellent.  Thanks!

**Comment by ErikEvenson** [comment]
You might consider using reverence (https://github.com/ntt/reverence) as an option for bulkdata import.  Thanks again.
