### ISSUE TITLE
Rubicon 1.0.4 datadump url

### ISSUE THREAD

**Issue by rhblind** [gtaylor/django-eve-db#17]
Hey,
Nice project, was just in the process of inspectdb'ing a mysql dump, but this might save me the trouble.

Can you please provide a working url for the rubicon 1.0.4 datadump?
Thanks

**Comment by zweizeichen** [comment]
No problem - http://files.zweizeichen.org/dump.zip
Please tell me if that works for you. You might also want to check out https://github.com/EVE-Tools/element43 if you're interested in an implementation.

**Comment by rhblind** [comment]
Thanks, worked!
I'm in the process of learning some backbone stuff, so I just needed a fun project to work on =)
I'll check out the implementation.

Take care =)
