### ISSUE TITLE
Data Dump Inconsistency

### ISSUE THREAD

**Issue by jzmiller1** [gtaylor/django-eve-db#23]
I ran into the following error loading the latest import:

django.db.utils.IntegrityError: insert or update on table "eve_db_invmarketgroup" violates foreign key constraint "eve_db_invmarket_parent_id_1f53341d_fk_eve_db_invmarketgroup_id"
DETAIL:  Key (parent_id)=(1361) is not present in table "eve_db_invmarketgroup".

I noticed that a similar problem was corrected on the thread of Issue #13 by @zweizeichen and was wondering if anyone might be able to give some advice on how to correct the data dump?  I am working with the latest sqlite dump from:

https://www.fuzzwork.co.uk/dump/

**Comment by zweizeichen** [comment]
Try looking at the SDE in an SQLite editor like Navicat or Base 2. I'm currently preparing the Tiamat SDE for Element43. I'll keep you updated if I run into any similar issues.

**Comment by jzmiller1** [comment]
Did you have any issues?  I was able to get the tables to load with an sqlite3 backend but it took many days.  The error I posted above was on a postgres backend.

**Comment by zweizeichen** [comment]
Importing the dump into a non-empty DB always takes a while. Even on our main server it took around 8 hours. The latest Scylla dump should work just fine. I had similar errors like yours during testing this time - even with a perfectly fine SQLite SDE. Deleting and re-creating the entire DB helped in those cases.
