### ISSUE TITLE
import fails as no XXX column in source db

### ISSUE THREAD

**Issue by dpwiz** [gtaylor/django-eve-db#3]
i'm using sqlite dump from this thread: http://www.eveonline.com/ingameboard.asp?a=topic&threadID=1376938

traceback tail:

```
eve_db/ccp_importer/importers/map.py in import_row(self, row)
    227         imp_obj.importance = row['importance']
    228 
--> 229         if row['url2d']:
    230             imp_obj.url_2d = row['url2d']
```

dgmAttributeTypes:

```
File "django-eve-db/eve_db/ccp_importer/importers/inventory.py", line 172, in import_row
    graphic_id = row['graphicID']
```

dgmEffects:

```
django-eve-db/eve_db/ccp_importer/importers/inventory.py(213)import_row()
--> 213         if row['graphicID']:
    214             imp_obj.graphic = EveGraphic.objects.get(id=row['graphicID'])
```

staStationTypes:

```
django-eve-db/eve_db/ccp_importer/importers/station.py(123)import_row()
--> 123         if row['dockingBayGraphicID']:
    124             imp_obj.docking_bay_graphic = EveGraphic.objects.get(id=row['dockingBayGraphicID'])
    125             
--> 126         if row['hangarGraphicID']:
    127             imp_obj.hangar_graphic = EveGraphic.objects.get(id=row['hangarGraphicID'])
```

**Comment by dpwiz** [comment]
I wonder why bother with conversion in the first place? There are DB-specific dumps for each major (and django-supported) engines and they are loading really fast...

**Comment by gtaylor** [comment]
The mapLandmarks one should be fixed as of late last night. The other three I'll be getting to today.

As far as the why, SQLite is the least common denominator. Some people want to run on SQLite, some want to run on MySQL, some want to run on Postgres, and a tiny amount want to run on Oracle. Each one of those conversions differs slightly. We initially tried to write DB-agnostic importers, but ended up having to make all kinds of RDBMs-specific consolations that were really sloppy.

The initial import does really take a long time, but ideally, you do that once every six months at most.

**Comment by gtaylor** [comment]
These bugs should be fixed in the latest master/develop branches.

**Comment by dpwiz** [comment]
Yeah, import completes fine now. Thanks!
