### ISSUE TITLE
Use of sqlite?

### ISSUE THREAD

**Issue by adelovett** [gtaylor/django-eve-db#4]
Out of curiosity, given that it appears other apps within this project make use of postgresql (or, presumably, mysql), is there any specific reason to use sqlite for eve-db rather than using the mysql/pgsql conversions so that everything can be handled within a single database system?

-aDe

**Comment by gtaylor** [comment]
We do not specifically depend on Postgres, MySQL, oracle, SQLite, or the community-maintained MSSQL RDBMS. We support all of these equally. That is the idea, anyway. If you can point out what bit of documentation or code might give the impression that we only support Postgres/MySQL, we'll improve it.

Each RDBMs has different constraints, capabilities, and quirks. Furthermore, each dump is slightly different, based on said quirks. For example, Postgres has very different rules about primary keys than MSSQL. This is a problem in that the MSSQL dump can't be converted to Postgres format without manipulations. However, SQLite has much more permissive rules in general, and can almost directly accept the original CCP data dump. I can't comment on MySQL, as I haven't used it in years.

The point with all of this is that we'd end up writing RDBMs-specific behaviors even if we used these "native" conversions. This means that we'd end up writing a lot of RDBMs-specific code, which is very hard to maintain. If nobody is using the Oracle models, who will maintain them? How would people get help if they tried to install django-eve-db on an Oracle server, but nobody was maintaining them? I don't care to maintain Oracle-specific models, I don't care to maintain MySQL-specific models. I want to maintain one set of models that works for every RDBMs that Django supports.

The way it is now, you have an admittedly way-too-slow import once every six months (each expansion). After that initial obstacle, the models are structured a little more cleanly and with Django practices in mind than a straight introspection of the dumps would yield (I tried that route initially). Field names have been slightly modified, and polish applied here and there. This may not be your cup of tea, but the end result feels a lot more like a typical Django app, and less like a really kludgey introspection of a weird set of tables.

So in essence, we chose the more tedious, slower route to be truely DB-agnostic.

**Comment by adelovett** [comment]
I was referring to the sqlite code in eve_db/ccp_importer, nothing else.  I understand the issues with the raw MSSQL dump and its conversions to sqlite/mysql/pgsql - was just wondering if it even made sense to offer mysql/pgsql versions of the importer code so that sqlite isn't needed at all.  I don't mind either way, just with the DB-agnostic approach of django in general, using a specific database (sqlite) for the import just jumped out at me.

**Comment by gtaylor** [comment]
Oh, ok I see what you're saying.

It's a possibility, but I'm not sure what gains you'd see. SQLite is included with Python 2.5 and up, so everyone should already have it. This removes the need for extra setup work for MySQL or Postgres. And for data like this, SQLite is actually really fast.

The slowness of the importer is mostly due to Django ORM overhead. So whether we used MySQL, Postgres, or something else, we'd see the same or maybe even slower performance.

Sorry for the confusion. Does this make more sense now? Everyone has SQLite, so it's the least common denominator. It's also very fast in single-user situations like this with relatively simple data.

**Comment by adelovett** [comment]
Yup, makes sense.  Like I said, the use of sqlite for the importer just jumped out at me as being slightly "odd" (for want of a better word).  I've got no problems with it -- I have other random tools running against the pgsql version of the datadump, but then again, once I get my head fully around django-eve, I could very well be able to rewrite them.

So, all good, thanks.  Chalk the issue up to an initial understanding curve, thanks for your input, and please go ahead and close it out.
